services:
    frontend:
        container_name: ${STACK_NAME}_frontend
        build:
            dockerfile: Dockerfile.linux
            args:
                PHP_VERSION: ${PHP_VERSION}
        environment:
            SERVER_NAME: ${SERVER_NAME}
            VIRTUAL_HOST: ${SERVER_NAME}
            LETSENCRYPT_HOST: ${SERVER_NAME}
        volumes:
            - /var/vhosts/${SERVER_NAME}/:/var/www/data/
        tmpfs:
            - /var/www/cache/:uid=33,gid=33
        networks:
            - vhosts
        expose:
            - 80
        restart: unless-stopped

networks:
    vhosts:
        external: true

