services:
    frontend:
        image: tmp/${STACK_NAME}:latest
        volumes:
            - data:/var/www/data
        networks:
            - vhosts_default
        deploy:
            mode: global
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s

volumes:
    data:

networks:
    vhosts_default:
        external: true