services:
    frontend:
        image: tmp/${STACK_NAME}:latest
        volumes:
            - data:C:/www/data
        ports:
            - 80:80
            - 443:443
        deploy:
            mode: global
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
volumes:
    data:
                