services:
    frontend:
        container_name: ${STACK_NAME}_frontend
        image: faulo/farah:${PHP_VERSION}
        volumes:
            - ../assets:${DOCKER_WORKDIR}/assets
            - ../cache:${DOCKER_WORKDIR}/cache
            - ../data:${DOCKER_WORKDIR}/data
            - ../html:${DOCKER_WORKDIR}/html
            - ../log:${DOCKER_WORKDIR}/log
            - ../src:${DOCKER_WORKDIR}/src
            - ../composer.json:${DOCKER_WORKDIR}/composer.json
        ports:
            - 80:80
